name: Portfolio API

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./src/Modules/Portfolio/Portfolio.Api/Portfolio.Api.csproj

      - name: Build
        run: dotnet build ./src/Modules/Portfolio/Portfolio.Api/Portfolio.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/Modules/Portfolio/Portfolio.Api/Portfolio.Api.csproj -c Release -o "$GITHUB_WORKSPACE/publish" --no-build