name: Build and deploy Node.js app to Azure Web App - portfolio-frontend-mathszoke

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify package.json
        run: cat ./src/Frontend/Frontend.Modules.UI/portfolio-web/package.json

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./src/Frontend/Frontend.Modules.UI/portfolio-web

      - name: Build project with Vite
        run: npm run build
        working-directory: ./src/Frontend/Frontend.Modules.UI/portfolio-web

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./src/Frontend/Frontend.Modules.UI/portfolio-web/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./dist

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'portfolio-frontend-mathszoke'
          slot-name: 'Production'
          package: './dist'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CF56042EEB52429E9F8F1C90B356EB2C }}
